[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
smart_contract = "4b3JKLWB4S6Xc1RTC22dtgksxSEzcordsMSZsUcWS5BN"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
